version: "3.9"

services:
  backend:
    tty: true
    container_name: back-container
    build:
      context: .
      dockerfile: containers/backend/Dockerfile

    volumes:
      - ./django_project:/code/django_project
    # ローカルのポート:コンテナのポート
    ports:
      - "8080:8080"
    command: >
      sh -c '
        python django_project/manage.py makemigrations --noinput &&
        python django_project/manage.py migrate --noinput &&
        # python django_project/manage.py collectstatic --noinput &&
        python django_project/manage.py runserver 0.0.0.0:8080
      '
    # 環境変数を.envを使って設定
    env_file:
      - .env
    networks:
      - backend_network

  frontend:
    tty: true
    container_name: front-container
    build:
      context: .
      dockerfile: containers/frontend/Dockerfile
    restart: always
    volumes:
      - ./front:/code/front
    command: sh -c "cd front && npm install &&WATCHPACK_POLLING=true npm start"
    ports:
      - "3000:3000"

networks:
  backend_network:
    driver: bridge
