FROM python:3.12.1

ENV PYTHONDONTWRITEBYTECODE=1

ENV PYTHONUNBUFFERED=1

WORKDIR /code
COPY ./backend/requirements-prod.txt /code/

RUN pip install --upgrade pip

RUN pip install -r requirements-prod.txt

COPY backend/ /code/

RUN ls

CMD ["sh", "entrypoint-prod.sh"]